[project]
name = "koreader-to-sioyek"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "regex>=2025.9.18",
    "sioyek>=0.31.2",
]
